package:
  name: scikit_build_example
  version: 0.0.1

source:
  path: ..

build:
  number: 0
  script: python -m pip install . -vv

requirements:
  build:
    - {{ compiler('cxx') }}
    - cmake >=3.18
    - ninja
    - make

  host:
    - python
    - pip
    - scikit-build-core
    - pybind11 >=2.6.0

  run:
    - python


test:
  imports:
    - scikit_build_example
  requires:
    - pytest
  source_files:
    - tests
  commands:
    - pytest tests

about:
  summary: An example project built with pybind11 and scikit-build.
  license_file: LICENSE
