package:
  name: scikit_build_example
  version: 0.0.1

source:
  path: ..

build:
  number: 0
  script: |
    PIP_NO_INDEX=OFF PIP_NO_DEPENDENCIES=OFF PIP_IGNORE_INSTALLED=OFF python -m pip install scikit-build-core  # [not win]
    set PIP_NO_INDEX=OFF&& set PIP_NO_DEPENDENCIES=OFF&& set PIP_IGNORE_INSTALLED=OFF&& python -m pip install scikit-build-core  # [win]
    python -m pip install . -vvv

requirements:
  build:
    - {{ compiler('cxx') }}

  host:
    - python
    - pip
    - cmake >=3.18
    - ninja
    - pybind11 >=2.6.0
    - distlib
    - exceptiongroup
    - importlib-resources
    - make
    - ninja
    - packaging
    - pathspec
    - pyproject-metadata
    - tomli
    - typing-extensions >=3.7

  run:
    - python


test:
  imports:
    - scikit_build_example
  requires:
    - pytest
  source_files:
    - tests
  commands:
    - pytest tests

about:
  summary: An example project built with pybind11 and scikit-build.
  license_file: LICENSE
