name: WASM

on:
  workflow_dispatch:
  pull_request:
    branches:
    - master

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  build-wasm-emscripten:
    name: Pyodide
    runs-on: ubuntu-22.04
    steps:
    - uses: actions/checkout@v4
      with:
        submodules: true
        fetch-depth: 0

    - uses: actions/setup-python@v5
      with:
        python-version: "3.12"

    - uses: pypa/cibuildwheel@v2.23
      env:
        CIBW_PLATFORM: pyodide

    - uses: actions/upload-artifact@v4
      with:
        path: dist/*.whl
